### ISSUE TITLE
Enable drag-and-drop

### ISSUE THREAD

**Issue by faradox** [okio-ai/nendo-web#5]
As a Nendo user, I want to be able to put tracks into collections by dragging-and-dropping them.

A package like https://github.com/SortableJS/vue.draggable.next could help.

See https://github.com/okio-ai/nendo-platform/discussions/34 for a related discussion

**Comment by samim23** [comment]
We already have "vuedraggable" (the repo referenced in the post above) as dependency in the frontend repo, which is used in the mashuper. Might be useful but it is a unmaintained 4 year old repo, so treat with caution.
